# Generated by Django 5.0.6 on 2024-10-25 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('insert_date', models.DateTimeField()),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dev_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ManqooRelations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('parking_name', models.CharField(blank=True, max_length=255, null=True)),
                ('database', models.CharField(blank=True, max_length=100, null=True)),
                ('start_rack', models.IntegerField(blank=True, null=True)),
                ('end_rack', models.IntegerField(blank=True, null=True)),
                ('machine_id', models.IntegerField(blank=True, null=True)),
                ('area_code', models.IntegerField(blank=True, null=True)),
                ('available_flag', models.IntegerField(blank=True, null=True)),
                ('empty_threshold', models.IntegerField(blank=True, null=True)),
                ('busy_threshold', models.IntegerField(blank=True, null=True)),
                ('vehicle_type', models.IntegerField(blank=True, null=True)),
                ('full_car_count', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('machine_type', models.IntegerField()),
            ],
            options={
                'db_table': 'manqoo_relations',
                'managed': False,
            },
        ),
    ]
